"""Run DPO from a verified SFT checkpoint and preference-pair JSONL.

Human-labelled pairs are mandatory unless the user explicitly opts into other
preference sources. No labels or preference model are generated by this script.
"""

from __future__ import annotations

import argparse
import json
import shutil
import tempfile
from pathlib import Path
from typing import Any

from training.common import DatasetError
from training.datasets.validate import validate_file
from training.model_registry import read_checkpoint_manifest, seal_checkpoint
from training.train_utils import (
    checkpoint_metadata,
    assert_disjoint_datasets,
    apply_qlora_override,
    load_json_dataset,
    load_yaml_config,
    require_cuda,
    require_training_dependencies,
    model_quantization_kwargs,
    prepare_kbit_model,
    qlora_metadata,
    summarize_dataset,
    supported_kwargs,
    validate_config,
)


_REQUIRED_CONFIG = {
    "seed", "max_length", "max_prompt_length", "num_train_epochs",
    "learning_rate", "per_device_train_batch_size", "per_device_eval_batch_size",
    "gradient_accumulation_steps", "beta", "loss_type", "bf16", "fp16",
    "gradient_checkpointing", "trust_remote_code", "model_adapter_name",
    "ref_adapter_name",
    "load_in_4bit", "local_files_only",
}

def _require_named_adapter_support(dpo_config_class: Any, trl_version: str) -> None:
    """Fail closed unless this TRL version exposes explicit policy/reference adapters."""
    fields = getattr(dpo_config_class, "__dataclass_fields__", {})
    required = {"model_adapter_name", "ref_adapter_name"}
    missing = sorted(required - set(fields))
    if missing:
        raise RuntimeError(
            f"Installed TRL {trl_version} cannot express an explicit PEFT DPO reference "
            f"through DPOConfig (missing {', '.join(missing)}). Refusing to train with "
            "an implicit base-model/reference fallback; install a TRL version that "
            "supports both named adapter fields."
        )


def _named_adapter_config_values(
    dpo_config_class: Any, values: dict[str, Any], *,
    policy_name: str, reference_name: str, trl_version: str,
) -> dict[str, Any]:
    _require_named_adapter_support(dpo_config_class, trl_version)
    if (
        not isinstance(policy_name, str)
        or not policy_name.strip()
        or not isinstance(reference_name, str)
        or not reference_name.strip()
        or policy_name == reference_name
    ):
        raise DatasetError("DPO policy and reference adapter names must be non-empty and distinct")
    configured = dict(values)
    configured["model_adapter_name"] = policy_name
    configured["ref_adapter_name"] = reference_name
    return configured


def _load_sft_adapter_pair(
    base_model: Any,
    checkpoint: str | Path,
    peft_model_class: Any,
    *,
    policy_name: str,
    reference_name: str,
) -> Any:
    """Load two copies of the SFT adapter: trainable policy and frozen reference."""
    checkpoint_path = str(Path(checkpoint).resolve())
    model = peft_model_class.from_pretrained(
        base_model, checkpoint_path, adapter_name=policy_name, is_trainable=True
    )
    model.load_adapter(
        checkpoint_path, adapter_name=reference_name, is_trainable=False
    )
    adapters = getattr(model, "peft_config", {})
    if policy_name not in adapters or reference_name not in adapters:
        raise RuntimeError(
            "PEFT did not load both requested SFT adapter copies; refusing DPO training"
        )
    model.set_adapter(policy_name)
    return model


def _validate_quantization_compatibility(parent: dict[str, Any], config: dict[str, Any]) -> None:
    """Keep DPO's reference base in the same quantization mode as its SFT parent."""
    parent_quantization = parent.get("quantization", {"enabled": False})
    if not isinstance(parent_quantization, dict):
        raise DatasetError("SFT checkpoint has invalid quantization provenance")
    parent_enabled = bool(parent_quantization.get("enabled", False))
    if parent_enabled != bool(config["load_in_4bit"]):
        raise DatasetError(
            "DPO quantization mode must match its verified SFT checkpoint so the frozen "
            "SFT reference uses the same base-model representation"
        )
    if parent_enabled:
        dtype = "bfloat16" if config["bf16"] else "float16"
        if parent_quantization.get("compute_dtype") != dtype:
            raise DatasetError(
                "DPO compute dtype must match the QLoRA SFT checkpoint for the frozen "
                "reference base"
            )


def _publish_policy_adapter(trainer: Any, output_dir: str | Path, policy_name: str) -> None:
    """Export just the trained policy adapter to the root PEFT layout."""
    output = Path(output_dir).resolve()
    if Path(policy_name).name != policy_name or policy_name in {".", ".."}:
        raise DatasetError("DPO policy adapter name must be a simple adapter identifier")
    with tempfile.TemporaryDirectory(prefix=".fomo-dpo-export-", dir=output.parent) as tmp:
        staged = Path(tmp) / "model"
        trainer.save_model(str(staged))
        # PEFT stores named adapters in per-adapter subdirectories. Its default
        # adapter is the sole standard exception and is saved directly at root.
        source = staged if policy_name == "default" else staged / policy_name
        config_file = source / "adapter_config.json"
        if not config_file.is_file():
            raise RuntimeError(
                f"DPO trainer did not save policy adapter {policy_name!r} in the expected "
                "PEFT layout; refusing to seal a non-loadable checkpoint"
            )
        adapter_files = [
            path for path in source.glob("adapter_model*")
            if path.is_file() and path.suffix in {".safetensors", ".bin", ".json"}
        ]
        if not any(path.suffix in {".safetensors", ".bin"} for path in adapter_files):
            raise RuntimeError(
                f"DPO policy adapter {policy_name!r} has no recognized adapter weights"
            )
        for path in [config_file, *adapter_files]:
            shutil.copy2(path, output / path.name)


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--train", required=True, help="Validated DPO training JSONL")
    parser.add_argument("--validation", required=True, help="Held-out DPO evaluation JSONL")
    parser.add_argument("--sft-checkpoint", required=True, help="Completed SFT checkpoint directory")
    parser.add_argument("--output-dir", required=True)
    qlora = parser.add_mutually_exclusive_group()
    qlora.add_argument("--qlora", dest="qlora", action="store_true", help="Opt into 4-bit NF4 QLoRA")
    qlora.add_argument("--no-qlora", dest="qlora", action="store_false", help="Use ordinary LoRA")
    parser.set_defaults(qlora=None)
    parser.add_argument("--config", default=str(Path(__file__).with_name("config.yaml")))
    parser.add_argument(
        "--allow-nonhuman-preferences", action="store_true",
        help="Explicitly allow provenance that is not human-ranked",
    )
    parser.add_argument(
        "--allow-possible-secrets", action="store_true",
        help="Explicitly continue despite automated API-key pattern warnings (not recommended)",
    )
    parser.add_argument("--dry-run", action="store_true", help="Validate inputs without importing GPU libraries")
    return parser.parse_args(argv)


def _preflight(
    args: argparse.Namespace, config: dict[str, Any]
) -> tuple[dict[str, Any], dict[str, Any], dict[str, Any]]:
    validate_config(config, _REQUIRED_CONFIG)
    policy_name = config["model_adapter_name"]
    reference_name = config["ref_adapter_name"]
    if (
        not isinstance(policy_name, str)
        or not policy_name.strip()
        or not isinstance(reference_name, str)
        or not reference_name.strip()
        or policy_name == reference_name
    ):
        raise DatasetError("DPO policy/reference adapter names must be distinct non-empty strings")
    parent = read_checkpoint_manifest(args.sft_checkpoint, verify_files=True)
    if parent.get("method") != "sft":
        raise DatasetError("DPO must start from a completed SFT checkpoint")
    _validate_quantization_compatibility(parent, config)
    if not (Path(args.sft_checkpoint) / "adapter_config.json").is_file():
        raise DatasetError(
            "DPO requires a completed PEFT SFT checkpoint with adapter_config.json "
            "so the frozen SFT reference can be loaded explicitly"
        )
    if Path(args.train).resolve() == Path(args.validation).resolve():
        raise DatasetError("Training and validation files must be different")
    human = not args.allow_nonhuman_preferences
    train_summary = summarize_dataset(args.train, "dpo", human_preferences=human)
    eval_summary = summarize_dataset(args.validation, "dpo", human_preferences=human)
    flagged = train_summary["possible_secret_records"] + eval_summary["possible_secret_records"]
    if flagged and not args.allow_possible_secrets:
        raise DatasetError(
            f"Possible credential patterns found in {flagged} record(s). Review/redact the data; "
            "to override the heuristic, pass --allow-possible-secrets explicitly."
        )
    validate_file(args.train, "dpo", human_preferences=human)
    validate_file(args.validation, "dpo", human_preferences=human)
    assert_disjoint_datasets(args.train, args.validation, "dpo")
    output = Path(args.output_dir).resolve()
    parent_path = Path(args.sft_checkpoint).resolve()
    if output == parent_path or parent_path in output.parents or output in parent_path.parents:
        raise DatasetError("DPO output and source SFT checkpoint directories must be separate")
    if output.exists() and (not output.is_dir() or any(output.iterdir())):
        raise DatasetError(f"Refusing to overwrite non-empty output directory: {output}")
    return parent, train_summary, eval_summary


def run(argv: list[str] | None = None) -> dict[str, Any] | None:
    args = _parse_args(argv)
    config = apply_qlora_override(load_yaml_config(args.config), args.qlora)
    parent, train_summary, eval_summary = _preflight(args, config)
    if args.dry_run:
        print(
            f"Dry run passed: {train_summary['examples']} preference pairs / "
            f"{eval_summary['examples']} validation pairs; source SFT checkpoint "
            f"{parent['checkpoint_id']} verified. No model was loaded and no checkpoint was created."
        )
        return None

    modules = require_training_dependencies(qlora=bool(config["load_in_4bit"]))
    torch = modules["torch"]
    from peft import PeftConfig, PeftModel
    from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, set_seed
    from trl import DPOConfig, DPOTrainer

    trl_version = getattr(modules["trl"], "__version__", "unknown")
    _require_named_adapter_support(DPOConfig, trl_version)
    require_cuda(torch, bf16=bool(config["bf16"]), fp16=bool(config["fp16"]))
    set_seed(int(config["seed"]))
    source = Path(args.sft_checkpoint).resolve()
    source_base = str(parent["base_model"])
    base_revision = parent.get("base_model_revision")
    model_kwargs: dict[str, Any] = {
        "revision": base_revision,
        "trust_remote_code": bool(config["trust_remote_code"]),
        "local_files_only": bool(config["local_files_only"]),
        "torch_dtype": torch.bfloat16 if config["bf16"] else (
            torch.float16 if config["fp16"] else "auto"
        ),
    }
    if config["load_in_4bit"]:
        compute_dtype = torch.bfloat16 if config["bf16"] else torch.float16
        model_kwargs.update(model_quantization_kwargs(True, BitsAndBytesConfig, compute_dtype))
    if base_revision is None:
        model_kwargs.pop("revision")
    if not (source / "adapter_config.json").is_file():
        raise DatasetError(
            "DPO requires a completed PEFT SFT checkpoint with adapter_config.json; "
            "a base/full-model directory cannot supply the required frozen SFT reference adapter"
        )
    adapter_config = PeftConfig.from_pretrained(str(source))
    base_name = str(adapter_config.base_model_name_or_path)
    if base_name != source_base:
        raise DatasetError(
            "SFT adapter base model does not match its verified checkpoint manifest"
        )
    base_model = AutoModelForCausalLM.from_pretrained(source_base, **model_kwargs)
    if config["load_in_4bit"]:
        from peft import prepare_model_for_kbit_training
        base_model = prepare_kbit_model(
            base_model,
            prepare_model_for_kbit_training,
            gradient_checkpointing=bool(config["gradient_checkpointing"]),
        )
    model = _load_sft_adapter_pair(
        base_model,
        source,
        PeftModel,
        policy_name=str(config["model_adapter_name"]),
        reference_name=str(config["ref_adapter_name"]),
    )
    tokenizer = AutoTokenizer.from_pretrained(
        str(source),
        trust_remote_code=bool(config["trust_remote_code"]),
        local_files_only=True,
    )
    if tokenizer.pad_token is None:
        if tokenizer.eos_token is None:
            raise RuntimeError("Tokenizer has neither a pad token nor an EOS token")
        tokenizer.pad_token = tokenizer.eos_token
    model.config.use_cache = False
    human_preferences = not args.allow_nonhuman_preferences
    train_dataset = load_json_dataset(
        args.train, "dpo", modules["datasets"], human_preferences=human_preferences
    )
    eval_dataset = load_json_dataset(
        args.validation, "dpo", modules["datasets"], human_preferences=human_preferences
    )
    output = Path(args.output_dir).resolve()
    output.mkdir(parents=True, exist_ok=True)

    evaluation_key = "eval_strategy" if "eval_strategy" in DPOConfig.__dataclass_fields__ else "evaluation_strategy"
    training_args = {
        "output_dir": str(output),
        "seed": int(config["seed"]),
        "max_length": int(config["max_length"]),
        "max_prompt_length": int(config["max_prompt_length"]),
        "num_train_epochs": float(config["num_train_epochs"]),
        "learning_rate": float(config["learning_rate"]),
        "per_device_train_batch_size": int(config["per_device_train_batch_size"]),
        "per_device_eval_batch_size": int(config["per_device_eval_batch_size"]),
        "gradient_accumulation_steps": int(config["gradient_accumulation_steps"]),
        "warmup_ratio": float(config.get("warmup_ratio", 0.03)),
        "weight_decay": float(config.get("weight_decay", 0.01)),
        "logging_steps": int(config.get("logging_steps", 10)),
        "eval_steps": int(config.get("eval_steps", 100)),
        "save_steps": int(config.get("save_steps", 100)),
        "save_total_limit": int(config.get("save_total_limit", 3)),
        "gradient_checkpointing": bool(config["gradient_checkpointing"]),
        "bf16": bool(config["bf16"]),
        "fp16": bool(config["fp16"]),
        "beta": float(config["beta"]),
        "loss_type": str(config["loss_type"]),
        "logging_strategy": "steps",
        "save_strategy": "steps",
        evaluation_key: "steps",
        "load_best_model_at_end": True,
        "metric_for_best_model": "eval_loss",
        "greater_is_better": False,
        "report_to": [],
        "run_name": output.name,
    }
    training_args = _named_adapter_config_values(
        DPOConfig,
        training_args,
        policy_name=str(config["model_adapter_name"]),
        reference_name=str(config["ref_adapter_name"]),
        trl_version=trl_version,
    )
    args_obj = DPOConfig(**supported_kwargs(DPOConfig, training_args))
    trainer_kwargs = {
        "model": model,
        # The named reference adapter is loaded above from the same SFT weights
        # and frozen. Never let TRL infer a base-model reference implicitly.
        "ref_model": None,
        "args": args_obj,
        "train_dataset": train_dataset,
        "eval_dataset": eval_dataset,
    }
    import inspect
    if "processing_class" in inspect.signature(DPOTrainer).parameters:
        trainer_kwargs["processing_class"] = tokenizer
    else:
        trainer_kwargs["tokenizer"] = tokenizer
    trainer = DPOTrainer(**trainer_kwargs)
    train_result = trainer.train()
    eval_metrics = trainer.evaluate()
    _publish_policy_adapter(trainer, output, str(config["model_adapter_name"]))
    tokenizer.save_pretrained(str(output))
    trainer.save_state()
    metrics = {"train": train_result.metrics, "evaluation": eval_metrics}
    (output / "fomo-training-metrics.json").write_text(
        json.dumps(metrics, indent=2, sort_keys=True, default=str) + "\n", encoding="utf-8"
    )
    metadata = checkpoint_metadata(
        method="dpo",
        base_model=source_base,
        base_model_revision=base_revision,
        base_model_license=str(parent["base_model_license"]),
        data=train_summary,
        eval_data=eval_summary,
        examples_trained=train_summary["examples"],
        config=config,
        extra={
            "parent_checkpoint_id": parent["checkpoint_id"],
            "parent_checkpoint_path": str(source),
            "policy_adapter": str(config["model_adapter_name"]),
            "reference_adapter": str(config["ref_adapter_name"]),
            "reference_policy": "frozen-copy-of-sft-adapter",
            "quantization": qlora_metadata(
                bool(config["load_in_4bit"]),
                "bfloat16" if config["bf16"] else ("float16" if config["fp16"] else None),
            ),
            "preference_source_policy": "human-only" if human_preferences else "explicitly-allowed-nonhuman",
            "validation_metrics": eval_metrics,
            "libraries": {
                name: getattr(modules[name], "__version__", "unknown")
                for name in (
                    "torch", "transformers", "datasets", "peft", "trl", "accelerate",
                    *(("bitsandbytes",) if config["load_in_4bit"] else ()),
                )
            },
        },
    )
    manifest = seal_checkpoint(output, metadata)
    print(
        f"DPO completed and checkpoint integrity manifest written: "
        f"{manifest['checkpoint_id']} ({output})"
    )
    print("This records the training run; it is not a claim of benchmark quality or production readiness.")
    return manifest


if __name__ == "__main__":
    run()